// Generated by CoffeeScript 1.7.1
(function() {
  var h, w;

  w = 500;

  h = 300;

  d3.csv('./data.csv', function(data) {
    var nest;
    nest = d3.nest().key(function(d) {
      return d.kind;
    }).key(function(d) {
      return d.label;
    }).entries(data);
    return boxPlot(d3.select('body').append('svg').attr({
      width: w,
      height: h
    }), nest);
  });

}).call(this);
